void input(char *nome, int tamanho, char *mensagem);
int escolha(void);
void limpar_buffer(void);
void header(void);
void confirmacao(void);
void ler_nome(char *nome);
void ler_data(char *data);
void ler_telefone(char *telefone);
void ler_cargo(char *cargo);
void limpar_espacos_laterais(char *str);
void ler_tipo(char *tipo);
void ler_ddd(char *ddd);