int validar_data(const char *data);
int validar_nome(const char *nome);
int validar_horario_servico(const char *hora_servico);
int validar_cpf(const char *cpf);
int validar_telefone(const char *telefone);
int validar_cargo(const char *cargo);
int validar_confirmacao(const char *resposta);
int cliente_existe(const char *cpf_procurado);
int buscar_nome_cliente(const char *cpf_procurado, char *nome);
int validar_data_agendamento(const char *data);
int funcionario_existe(const char *cpf_procurado);